# docker-compose.yml
version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/backend
      - PYTHONUNBUFFERED=1
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network
    extra_hosts:
      - "api.bitfinex.com:104.16.174.181"  # Add Bitfinex API IP

networks:
  app-network:
    driver: bridge